spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 10000   # pool 연결 대기 최대 10s (기본 30s → 단축)

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  storage:
    type: local
    local:
      upload-dir: ${APP_STORAGE_LOCAL_UPLOAD_DIR:./uploads}
    oci:
      prefix: dev/

custom:
  swagger:
    enabled: true

logging:
  level:
    root: INFO
    back: DEBUG
