version: "3.8"

services:
  app-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-dev
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      FASTAPI_BASE_URL: ${FASTAPI_BASE_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ai-service
    networks:
      - app-network

  ai-service:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    env_file:
      - ../ai-service/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
