global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "spring-canary"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["back-app-canary:8080"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
