global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus-cloud:9090"]

  - job_name: "spring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app-dev:8080"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki-cloud:3100"]
