apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-cloud:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"
      exemplarTraceIdDestinations: []

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-cloud:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"(\w+)"'
          url: ""
